sudo: false
language: node_js
node_js:
  - "node"
branches:
  only:
    - master
cache:
  directories:
  - node_modules
before_install:
- yarn update
install:
- yarn install
script:
- yarn run lint
- yarn test
- yarn run coveralls
