sudo: false
language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
before_install:
- yarn upgrade
install:
- yarn install
script:
- yarn run lint
- yarn test
- yarn run coveralls
