export const UNAUTH_USER = 'UNAUTH_USER';

export const FETCH_BANNER = 'FETCH_BANNER';

export const EVENT_CHECKIN = 'EVENT_CHECKIN';
export const FETCH_FUTURE_EVENTS = 'FETCH_FUTURE_EVENTS';
export const FETCH_PAST_EVENTS = 'FETCH_PAST_EVENTS';

export const FETCH_USER = 'FETCH_USER';
