export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';

export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_BANNER = 'FETCH_BANNER';

export const EVENT_CHECKIN = 'EVENT_CHECKIN';
export const FETCH_FUTURE_EVENTS = 'FETCH_FUTURE_EVENTS';
export const FETCH_PAST_EVENTS = 'FETCH_PAST_EVENTS';

export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const LEADERBOARD_ERROR = 'LEADERBOARD_ERROR';

export const FETCH_USER = 'FETCH_USER';
