name: 'Add Label to Fully-Reviewed PR'
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: Add approval label
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: 2
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "PR: Good to Merge"
          REMOVE_LABEL: |
            "PR: Needs Review"
            "PR: Reviewed w/ Comments"